const getNewsSources = [
  "ABC News",
  "Aftenposten",
  "Al Jazeera English",
  "Argaam",
  "Ars Technica",
  "Ary News",
  "Associated Press",
  "Australian Financial Review",
  "Axios",
  "BBC News",
  "BBC Sport",
  "Bild",
  "Bleacher Report",
  "Bloomberg",
  "Breitbart News",
  "Buzzfeed",
  "CBC News",
  "CBS News",
  "CNN",
  "Crypto Coins News",
  "Der Tagesspiegel",
  "Die Zeit",
  "Engadget",
  "Entertainment Weekly",
  "ESPN",
  "Financial Post",
  "Focus",
  "Football Italia",
  "Fortune",
  "FourFourTwo",
  "Fox News",
  "Fox Sports",
  "Globo",
  "Google News",

  "Gruenderszene",
  "Hacker News",
  "Handelsblatt",
  "IGN",
  "Independent",
  "Infobae",
  "La Gaceta",
  "La Nacion",
  "La Repubblica",
  "Le Monde",
  "Lenta",
  "Les Echos",
  "Marca",
  "Mashable",
  "Medical News Today",
  "MSNBC",
  "MTV News",
  "National Geographic",
  "National Review",
  "NBC News",
  "New Scientist",
  "Newsweek",
  "New York Magazine",
  "Next Big Future",
  "NFL News",
  "NHL News",
  "NRK",
  "Politico",
  "Polygon",
  "RBC",
  "Recode",
  "Reuters",
  "RT",
  "RTE",
  "RTL Nieuws",
  "SABQ",
  "Spiegel Online",
  "Svenska Dagbladet",
  "T3n",
  "TechCrunch",
  "TechRadar",
  "The American Conservative",
  "The Globe And Mail",
  "The Hill",
  "The Hindu",
  "The Huffington Post",
  "The Irish Times",
  "The Jerusalem Post",
  "The Lad Bible",
  "The Next Web",
  "The Sport Bible",
  "The Times of India",
  "The Verge",
  "The Wall Street Journal",
  "The Washington Post",
  "The Washington Times",
  "Time",
  "USA Today",
  "Vice News",
  "Wired",
  "Wirtschafts Woche",
  "Xinhua Net",
  "Ynet",
];

export default getNewsSources;
